version: '3'

services:
  echo-service:
    build:
      context: .
      args:
        - PORT=${PORT}
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    container_name: echo-service
    image: echo-service:latest
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    command:
      - /echo
